apiVresion: apps/v1
kind: Deployment
metadata:
 name: blogging-app-deployment
 labels:
  app: game
spec:
 replicas: 2
 selector:
  matchLabels:
   app: game
 template:
  metadata:
   name: blogging-app-pod
   labels:
    app: game
  spec:
   containers:
    - name: blogging-app-containers
      image: blogging-app
      ports:
       - containerPort: 8080